# Preparações

In [ ]:
!pip install pycaret==2.3.10 markupsafe==2.0.1 pyyaml==5.4.1 -qq

     |████████████████████████████████| 320 kB 5.1 MB/s
     |████████████████████████████████| 636 kB 17.6 MB/s
     |████████████████████████████████| 6.8 MB 9.0 MB/s
     |████████████████████████████████| 262 kB 59.2 MB/s
     |████████████████████████████████| 88 kB 6.1 MB/s
     |████████████████████████████████| 17.8 MB 54.5 MB/s
     |████████████████████████████████| 10.4 MB 17.3 MB/s
     |████████████████████████████████| 1.3 MB 65.4 MB/s
     |████████████████████████████████| 167 kB 3.2 MB/s
     |████████████████████████████████| 122 kB 55.9 MB/s
     |████████████████████████████████| 1.7 MB 43.7 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 2.0 MB 7.3 MB/s
     |████████████████████████████████| 56 kB 4.9 MB/s
     |████████████████████████████████| 1.3 MB 54.8 MB/s
     |████████████████████████████████| 261 kB 27.8 MB/s
     |████████████████████████████████| 3.1 MB 57.4 MB/s
     |████████████████████████████████| 690 kB 61.5 MB/s
     |████████████████████████████████| 62 kB 1.5 MB/s
     |████████████████████████████████| 303 kB 8.6 MB/s
     |████████████████████████████████| 102 kB 11.9 MB/s
     |████████████████████████████████| 812 kB 59.4 MB/s
     |████████████████████████████████| 25.9 MB 71.5 MB/s
     |████████████████████████████████| 1.0 MB 43.2 MB/s
     |████████████████████████████████| 184 kB 63.2 MB/s
     |████████████████████████████████| 271 kB 61.0 MB/s
     |████████████████████████████████| 14.8 MB 65.1 MB/s
     |████████████████████████████████| 79 kB 8.0 MB/s
     |████████████████████████████████| 209 kB 67.1 MB/s
     |████████████████████████████████| 146 kB 57.8 MB/s
     |████████████████████████████████| 81 kB 9.5 MB/s
     |████████████████████████████████| 181 kB 51.0 MB/s
     |████████████████████████████████| 54 kB 2.3 MB/s
     |████████████████████████████████| 63 kB 1.6 MB/s
     |████████████████████████████████| 78 kB 6.9 MB/s
     |████████████████████████████████| 1.7 MB 57.0 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 1.7 MB 48.5 MB/s
     |████████████████████████████████| 1.1 MB 53.9 MB/s
  Building wheel for htmlmin (setup.py) ... done
  Building wheel for imagehash (setup.py) ... done
  Building wheel for databricks-cli (setup.py) ... done
  Building wheel for pyLDAvis (setup.py) ... done
  Building wheel for pyod (setup.py) ... done
  Building wheel for umap-learn (setup.py) ... done
  Building wheel for pynndescent (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xarray-einstats 0.2.2 requires numpy>=1.21, but you have numpy 1.19.5 which is incompatible.
tensorflow 2.8.2+zzzcolab20220527125636 requires numpy>=1.20, but you have numpy 1.19.5 which is incompatible.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.28.0 which is incompatible.
en-core-web-sm 3.3.0 requires spacy<3.4.0,>=3.3.0.dev0, but you have spacy 2.3.7 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.

In [ ]:
import pandas as pd
from pycaret.classification import *
from tqdm import tqdm

/usr/local/lib/python3.7/dist-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

# Preparação

In [ ]:
df_train_values = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/train_values.csv")

In [ ]:
df_train__label_values = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/train_labels.csv")

In [ ]:
df_train_values.head()

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,legal_ownership_status,count_families,has_secondary_use,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,802906,6,487,12198,2,30,6,5,t,r,n,f,q,t,d,1,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
1,28830,8,900,2812,2,10,8,7,o,r,n,x,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
2,94947,21,363,8973,2,10,5,5,t,r,n,f,x,t,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
3,590882,22,418,10694,2,10,6,5,t,r,n,f,x,s,d,0,1,0,0,0,0,1,1,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
4,201944,11,131,1488,3,30,8,9,t,r,n,f,x,s,d,1,0,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
df_train__label_values.head()

   building_id  damage_grade
0       802906             3
1        28830             2
2        94947             3
3       590882             2
4       201944             3

In [ ]:
print(df_train_values.shape)
print(df_train__label_values.shape)

(260601, 39)
(260601, 2)

In [ ]:
df_train = pd.merge(df_train_values,df_train__label_values,how='inner',on='building_id')

In [ ]:
print(df_train_values.shape)
print(df_train__label_values.shape)
print(df_train.shape)

(260601, 39)
(260601, 2)
(260601, 40)

In [ ]:
df_train.damage_grade.value_counts()

2    148259
3     87218
1     25124
Name: damage_grade, dtype: int64

In [ ]:
target = []

for n in df_train.damage_grade:
    if n == 1:
        target.append(0)
    elif n == 2:
        target.append(1)
    elif n == 3:
        target.append(2)

In [ ]:
df_train["damage_grade"] = target

In [ ]:
df_train.damage_grade.value_counts()

1    148259
2     87218
0     25124
Name: damage_grade, dtype: int64

In [ ]:
df_teste = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/test_values.csv")

In [ ]:
df_teste.head()

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,legal_ownership_status,count_families,has_secondary_use,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,300051,17,596,11307,3,20,7,6,t,r,n,f,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
1,99355,6,141,11987,2,25,13,5,t,r,n,f,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,1,1,0,0,0,0,0,0,0,0,0
2,890251,22,19,10044,2,5,4,5,t,r,n,f,q,s,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0
3,745817,26,39,633,1,0,19,3,t,r,x,v,j,t,d,0,0,0,0,0,1,0,0,0,0,0,v,2,1,0,0,1,0,0,0,0,0,0,0
4,421793,17,289,7970,3,15,8,7,t,r,q,f,q,t,d,0,1,0,0,0,0,0,0,0,0,0,v,1,0,0,0,0,0,0,0,0,0,0,0

# Treinamentos

In [ ]:
clf1 = setup(data = df_train, target = 'damage_grade', session_id = 786, silent = True, use_gpu=True)

                               Description             Value
0                               session_id               786
1                                   Target      damage_grade
2                              Target Type        Multiclass
3                            Label Encoded              None
4                            Original Data      (260601, 40)
5                           Missing Values             False
6                         Numeric Features                 7
7                     Categorical Features                32
8                         Ordinal Features             False
9                High Cardinality Features             False
10                 High Cardinality Method              None
11                   Transformed Train Set      (182420, 86)
12                    Transformed Test Set       (78181, 86)
13                      Shuffle Train-Test              True
14                     Stratify Train-Test             False
15                          Fold Generator   StratifiedKFold
16                             Fold Number                10
17                                CPU Jobs                -1
18                                 Use GPU              True
19                          Log Experiment             False
20                         Experiment Name  clf-default-name
21                                     USI              c56f
22                         Imputation Type            simple
23          Iterative Imputation Iteration              None
24                         Numeric Imputer              mean
25      Iterative Imputation Numeric Model              None
26                     Categorical Imputer          constant
27  Iterative Imputation Categorical Model              None
28           Unknown Categoricals Handling    least_frequent
29                               Normalize             False
30                        Normalize Method              None
31                          Transformation             False
32                   Transformation Method              None
33                                     PCA             False
34                              PCA Method              None
35                          PCA Components              None
36                     Ignore Low Variance             False
37                     Combine Rare Levels             False
38                    Rare Level Threshold              None
39                         Numeric Binning             False
40                         Remove Outliers             False
41                      Outliers Threshold              None
42                Remove Multicollinearity             False
43             Multicollinearity Threshold              None
44             Remove Perfect Collinearity              True
45                              Clustering             False
46                    Clustering Iteration              None
47                     Polynomial Features             False
48                       Polynomial Degree              None
49                    Trignometry Features             False
50                    Polynomial Threshold              None
51                          Group Features             False
52                       Feature Selection             False
53                Feature Selection Method           classic
54            Features Selection Threshold              None
55                     Feature Interaction             False
56                           Feature Ratio             False
57                   Interaction Threshold              None
58                           Fix Imbalance             False
59                    Fix Imbalance Method             SMOTE

In [ ]:
%%time
best_model = compare_models()

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
lightgbm,Light Gradient Boosting Machine,0.7104,0.8043,0.6095,0.7115,0.7004,0.4429,0.4540,2.385
rf,Random Forest Classifier,0.7087,0.8028,0.6146,0.7079,0.7001,0.4438,0.4525,14.526
et,Extra Trees Classifier,0.6895,0.7810,0.6047,0.6857,0.6829,0.4149,0.4196,20.463
gbc,Gradient Boosting Classifier,0.6814,0.7715,0.5662,0.6858,0.6643,0.3737,0.3934,152.347
ada,Ada Boost Classifier,0.6470,0.6698,0.5197,0.6615,0.6147,0.2869,0.3220,11.883
dt,Decision Tree Classifier,0.6409,0.6727,0.5919,0.6424,0.6416,0.3571,0.3572,2.811
ridge,Ridge Classifier,0.5924,0.0000,0.4329,0.5851,0.5332,0.1420,0.1764,0.376
lda,Linear Discriminant Analysis,0.5897,0.6568,0.5123,0.5803,0.5504,0.1913,0.2126,2.822
lr,Logistic Regression,0.5681,0.4974,0.3333,0.3227,0.4116,0.0000,0.0000,10.865
dummy,Dummy Classifier,0.5681,0.5000,0.3333,0.3227,0.4116,0.0000,0.0000,0.089
nb,Naive Bayes,0.5654,0.5773,0.3343,0.3368,0.4122,0.0004,0.0020,0.340
qda,Quadratic Discriminant Analysis,0.4953,0.5019,0.3636,0.4567,0.4450,0.0120,0.0134,1.173
knn,K Neighbors Classifier,0.4933,0.5035,0.3357,0.4465,0.4591,0.0020,0.0021,4.948
svm,SVM - Linear Kernel,0.3771,0.0000,0.3337,0.3774,0.2374,-0.0003,0.0044,52.634

CPU times: user 1h 3min 24s, sys: 11min 10s, total: 1h 14min 34s
Wall time: 46min 22s

In [ ]:
%%time

dt1 = create_model('lightgbm')
dt2 = create_model('rf')
dt3 = create_model('et')
dt4 = create_model('gbc')
dt5 = create_model('ada')
dt6 = create_model('dt')
dt7 = create_model('ridge')
dt8 = create_model('lda')
dt9 = create_model('nb')
dt10 = create_model('qda')

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
Fold
0       0.4745  0.5035  0.3828  0.4647  0.4677  0.0201  0.0201
1       0.4473  0.4865  0.3303  0.4345  0.4403 -0.0210 -0.0211
2       0.5326  0.5005  0.3394  0.4526  0.4361  0.0034  0.0049
3       0.4760  0.5102  0.4224  0.4553  0.4577  0.0396  0.0406
4       0.5123  0.5009  0.3380  0.4484  0.4684  0.0073  0.0078
5       0.5628  0.4994  0.3337  0.4886  0.4217 -0.0007 -0.0021
6       0.5467  0.5005  0.3532  0.4551  0.4303  0.0078  0.0135
7       0.4126  0.5176  0.4122  0.4633  0.4201  0.0461  0.0486
8       0.4770  0.4938  0.3467  0.4493  0.4582 -0.0062 -0.0063
9       0.5116  0.5063  0.3773  0.4550  0.4496  0.0241  0.0281
Mean    0.4953  0.5019  0.3636  0.4567  0.4450  0.0120  0.0134
Std     0.0441  0.0081  0.0317  0.0133  0.0170  0.0196  0.0204

CPU times: user 42min 3s, sys: 2min 9s, total: 44min 12s
Wall time: 38min 38s

In [ ]:
%%time

tuned_dt1 = tune_model(dt1, optimize = 'F1')

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
Fold
0       0.7212  0.8161  0.6312  0.7211  0.7136  0.4691  0.4773
1       0.7285  0.8204  0.6381  0.7297  0.7207  0.4817  0.4908
2       0.7239  0.8143  0.6353  0.7246  0.7162  0.4737  0.4826
3       0.7250  0.8182  0.6310  0.7247  0.7173  0.4762  0.4842
4       0.7204  0.8138  0.6250  0.7196  0.7127  0.4680  0.4757
5       0.7213  0.8127  0.6268  0.7207  0.7135  0.4692  0.4771
6       0.7222  0.8150  0.6275  0.7222  0.7141  0.4700  0.4787
7       0.7208  0.8174  0.6265  0.7206  0.7128  0.4674  0.4757
8       0.7241  0.8170  0.6331  0.7243  0.7165  0.4745  0.4827
9       0.7201  0.8135  0.6299  0.7201  0.7123  0.4666  0.4748
Mean    0.7227  0.8158  0.6304  0.7228  0.7150  0.4716  0.4800
Std     0.0025  0.0023  0.0040  0.0030  0.0025  0.0045  0.0048

CPU times: user 5min 46s, sys: 2.13 s, total: 5min 48s
Wall time: 3min 31s

In [ ]:
tuned_dt1

LGBMClassifier(bagging_fraction=0.6, bagging_freq=1, boosting_type='gbdt',
               class_weight=None, colsample_bytree=1.0, feature_fraction=0.4,
               importance_type='split', learning_rate=0.3, max_depth=-1,
               min_child_samples=61, min_child_weight=0.001, min_split_gain=0.1,
               n_estimators=190, n_jobs=-1, num_leaves=20, objective=None,
               random_state=786, reg_alpha=1e-06, reg_lambda=5, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:
predict_tuned_dt1 = predict_model(tuned_dt1, data=df_teste).Label

sub_csv = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/submission_format.csv")
sub_csv["damage_grade"] = predict_tuned_dt1
sub_csv.to_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/output/submit/predict_tuned_dt1.csv", index=False)

In [ ]:
%%time

tuned_dt2 = tune_model(dt2, optimize = 'F1')

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
Fold
0       0.5593  0.7158  0.6314  0.6234  0.5598  0.3064  0.3267
1       0.5753  0.7245  0.6414  0.6332  0.5764  0.3247  0.3435
2       0.5594  0.7159  0.6349  0.6261  0.5605  0.3088  0.3296
3       0.5625  0.7222  0.6332  0.6275  0.5632  0.3117  0.3324
4       0.5595  0.7241  0.6361  0.6330  0.5614  0.3137  0.3364
5       0.5487  0.7142  0.6264  0.6227  0.5508  0.2991  0.3212
6       0.5601  0.7194  0.6386  0.6328  0.5624  0.3148  0.3371
7       0.5640  0.7177  0.6351  0.6295  0.5653  0.3142  0.3348
8       0.5679  0.7231  0.6430  0.6360  0.5690  0.3221  0.3439
9       0.5627  0.7153  0.6361  0.6276  0.5633  0.3124  0.3332
Mean    0.5619  0.7192  0.6356  0.6292  0.5632  0.3128  0.3339
Std     0.0065  0.0038  0.0045  0.0043  0.0063  0.0069  0.0067

CPU times: user 1min 7s, sys: 1.31 s, total: 1min 9s
Wall time: 9min 5s

In [ ]:
tuned_dt2

RandomForestClassifier(bootstrap=False, ccp_alpha=0.0,
                       class_weight='balanced_subsample', criterion='gini',
                       max_depth=5, max_features=1.0, max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0005,
                       min_impurity_split=None, min_samples_leaf=5,
                       min_samples_split=7, min_weight_fraction_leaf=0.0,
                       n_estimators=40, n_jobs=-1, oob_score=False,
                       random_state=786, verbose=0, warm_start=False)

In [ ]:
predict_tuned_dt2 = predict_model(tuned_dt2, data=df_teste).Label

sub_csv = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/submission_format.csv")
sub_csv["damage_grade"] = predict_tuned_dt2
sub_csv.to_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/output/submit/predict_tuned_dt2.csv", index=False)

In [ ]:
%%time

tuned_dt3 = tune_model(dt3, optimize = 'F1')

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
Fold
0       0.5209  0.6737  0.5972  0.5997  0.5072  0.2509  0.2822
1       0.5304  0.6778  0.5962  0.5932  0.5235  0.2543  0.2773
2       0.5207  0.6764  0.5938  0.5910  0.5107  0.2456  0.2719
3       0.5263  0.6781  0.5945  0.5940  0.5172  0.2511  0.2767
4       0.5209  0.6792  0.5889  0.5979  0.5079  0.2490  0.2795
5       0.5232  0.6699  0.5862  0.5833  0.5162  0.2428  0.2644
6       0.5191  0.6760  0.5910  0.5892  0.5075  0.2436  0.2708
7       0.5276  0.6776  0.5947  0.5888  0.5204  0.2504  0.2728
8       0.5277  0.6796  0.6044  0.5999  0.5169  0.2573  0.2855
9       0.5294  0.6741  0.5950  0.5897  0.5233  0.2525  0.2739
Mean    0.5246  0.6762  0.5942  0.5927  0.5151  0.2497  0.2755
Std     0.0039  0.0028  0.0047  0.0051  0.0061  0.0044  0.0058

CPU times: user 1min 19s, sys: 3.64 s, total: 1min 23s
Wall time: 6min 48s

In [ ]:
tuned_dt3

ExtraTreesClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                     criterion='gini', max_depth=10, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0, min_impurity_split=None,
                     min_samples_leaf=6, min_samples_split=7,
                     min_weight_fraction_leaf=0.0, n_estimators=190, n_jobs=-1,
                     oob_score=False, random_state=786, verbose=0,
                     warm_start=False)

In [ ]:
predict_tuned_dt3 = predict_model(tuned_dt3, data=df_teste).Label

sub_csv = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/submission_format.csv")
sub_csv["damage_grade"] = predict_tuned_dt3
sub_csv.to_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/output/submit/predict_tuned_dt3.csv", index=False)

In [ ]:
%%time

tuned_dt4 = tune_model(dt4, optimize = 'F1')

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
Fold
0       0.7127  0.8055  0.6321  0.7099  0.7072  0.4607  0.4650
1       0.7153  0.8054  0.6358  0.7129  0.7099  0.4653  0.4698
2       0.7159  0.8040  0.6386  0.7135  0.7107  0.4674  0.4718
3       0.7168  0.8078  0.6286  0.7137  0.7109  0.4673  0.4716
4       0.7142  0.8080  0.6322  0.7109  0.7091  0.4650  0.4685
5       0.7130  0.8054  0.6291  0.7099  0.7075  0.4614  0.4655
6       0.7134  0.8071  0.6316  0.7103  0.7083  0.4631  0.4668
7       0.7192  0.8089  0.6427  0.7165  0.7146  0.4751  0.4787
8       0.7123  0.8068  0.6335  0.7096  0.7070  0.4603  0.4644
9       0.7110  0.8055  0.6260  0.7079  0.7053  0.4570  0.4611
Mean    0.7144  0.8064  0.6330  0.7115  0.7090  0.4642  0.4683
Std     0.0023  0.0014  0.0047  0.0024  0.0025  0.0048  0.0047

CPU times: user 39min 50s, sys: 3.88 s, total: 39min 54s
Wall time: 1h 9min 4s

In [ ]:
tuned_dt4

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.2, loss='deviance', max_depth=9,
                           max_features=1.0, max_leaf_nodes=None,
                           min_impurity_decrease=0, min_impurity_split=None,
                           min_samples_leaf=5, min_samples_split=4,
                           min_weight_fraction_leaf=0.0, n_estimators=180,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=786, subsample=0.2, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [ ]:
predict_tuned_dt4 = predict_model(tuned_dt4, data=df_teste).Label

sub_csv = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/submission_format.csv")
sub_csv["damage_grade"] = predict_tuned_dt4
sub_csv.to_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/output/submit/predict_tuned_dt4.csv", index=False)

In [ ]:
%%time

tuned_dt5 = tune_model(dt5, optimize = 'F1')

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
Fold
0       0.6507  0.6793  0.5165  0.6649  0.6183  0.2913  0.3274
1       0.6523  0.6842  0.5191  0.6677  0.6193  0.2935  0.3310
2       0.6469  0.6807  0.5116  0.6636  0.6110  0.2794  0.3191
3       0.6526  0.6850  0.5148  0.6680  0.6200  0.2940  0.3311
4       0.6526  0.6860  0.5102  0.6666  0.6207  0.2947  0.3305
5       0.6467  0.6810  0.5104  0.6605  0.6139  0.2832  0.3187
6       0.6437  0.6799  0.5075  0.6528  0.6119  0.2785  0.3107
7       0.6486  0.6792  0.5114  0.6627  0.6155  0.2861  0.3224
8       0.6548  0.6841  0.5200  0.6711  0.6223  0.2986  0.3364
9       0.6466  0.6769  0.5142  0.6578  0.6149  0.2847  0.3182
Mean    0.6495  0.6816  0.5136  0.6636  0.6168  0.2884  0.3245
Std     0.0034  0.0029  0.0039  0.0051  0.0037  0.0066  0.0075

CPU times: user 8min 28s, sys: 2.28 s, total: 8min 31s
Wall time: 22min 21s

In [ ]:
tuned_dt5

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.4,
                   n_estimators=190, random_state=786)

In [ ]:
predict_tuned_dt5 = predict_model(tuned_dt5, data=df_teste).Label

sub_csv = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/submission_format.csv")
sub_csv["damage_grade"] = predict_tuned_dt5
sub_csv.to_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/output/submit/predict_tuned_dt5.csv", index=False)

In [ ]:
%%time

tuned_dt6 = tune_model(dt6, optimize = 'F1')

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
Fold
0       0.6700  0.7559  0.5374  0.6664  0.6548  0.3582  0.3676
1       0.6743  0.7596  0.5442  0.6730  0.6593  0.3653  0.3757
2       0.6705  0.7539  0.5150  0.6734  0.6475  0.3432  0.3611
3       0.6696  0.7592  0.5478  0.6638  0.6571  0.3635  0.3711
4       0.6725  0.7608  0.5676  0.6670  0.6635  0.3769  0.3826
5       0.6734  0.7545  0.5668  0.6696  0.6627  0.3735  0.3819
6       0.6679  0.7561  0.5524  0.6623  0.6565  0.3622  0.3695
7       0.6735  0.7585  0.5332  0.6733  0.6563  0.3608  0.3719
8       0.6682  0.7593  0.5376  0.6628  0.6537  0.3566  0.3654
9       0.6707  0.7525  0.5396  0.6668  0.6558  0.3598  0.3695
Mean    0.6711  0.7570  0.5442  0.6678  0.6567  0.3620  0.3716
Std     0.0021  0.0027  0.0149  0.0041  0.0043  0.0088  0.0065

CPU times: user 19.6 s, sys: 1.03 s, total: 20.6 s
Wall time: 30.5 s

In [ ]:
tuned_dt6

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=12, max_features=1.0, max_leaf_nodes=None,
                       min_impurity_decrease=0.0005, min_impurity_split=None,
                       min_samples_leaf=6, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=786, splitter='best')

In [ ]:
predict_tuned_dt6 = predict_model(tuned_dt6, data=df_teste).Label

sub_csv = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/submission_format.csv")
sub_csv["damage_grade"] = predict_tuned_dt6
sub_csv.to_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/output/submit/predict_tuned_dt6.csv", index=False)

In [ ]:
%%time

tuned_dt7 = tune_model(dt7, optimize = 'F1')

      Accuracy  AUC  Recall   Prec.      F1   Kappa     MCC
Fold
0       0.5936  0.0  0.4386  0.5859  0.5354  0.1464  0.1809
1       0.5967  0.0  0.4378  0.5926  0.5366  0.1492  0.1868
2       0.5893  0.0  0.4271  0.5807  0.5294  0.1345  0.1676
3       0.5898  0.0  0.4303  0.5794  0.5317  0.1384  0.1704
4       0.5959  0.0  0.4353  0.5918  0.5385  0.1509  0.1864
5       0.5892  0.0  0.4326  0.5791  0.5300  0.1366  0.1693
6       0.5946  0.0  0.4334  0.5892  0.5362  0.1469  0.1821
7       0.5934  0.0  0.4316  0.5876  0.5333  0.1424  0.1780
8       0.5906  0.0  0.4307  0.5831  0.5301  0.1363  0.1704
9       0.5909  0.0  0.4316  0.5817  0.5307  0.1388  0.1730
Mean    0.5924  0.0  0.4329  0.5851  0.5332  0.1420  0.1765
Std     0.0026  0.0  0.0033  0.0048  0.0031  0.0056  0.0069

CPU times: user 7.44 s, sys: 10.4 s, total: 17.9 s
Wall time: 11.2 s

In [ ]:
tuned_dt7

RidgeClassifier(alpha=0.72, class_weight=None, copy_X=True, fit_intercept=False,
                max_iter=None, normalize=True, random_state=786, solver='auto',
                tol=0.001)

In [ ]:
predict_tuned_dt7 = predict_model(tuned_dt7, data=df_teste).Label

sub_csv = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/submission_format.csv")
sub_csv["damage_grade"] = predict_tuned_dt7
sub_csv.to_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/output/submit/predict_tuned_dt7.csv", index=False)

In [ ]:
%%time

tuned_dt8 = tune_model(dt8, optimize = 'F1')

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
Fold
0       0.5852  0.6519  0.5164  0.5782  0.5358  0.1804  0.2062
1       0.5910  0.6559  0.5101  0.5816  0.5386  0.1813  0.2107
2       0.5711  0.6521  0.5484  0.5696  0.5699  0.2284  0.2286
3       0.5864  0.6578  0.5081  0.5781  0.5371  0.1777  0.2039
4       0.5754  0.6554  0.5007  0.5824  0.5012  0.1470  0.1826
5       0.5696  0.6419  0.5154  0.5781  0.5090  0.1589  0.1860
6       0.5852  0.6561  0.5115  0.5843  0.5327  0.1773  0.2054
7       0.5824  0.6564  0.5070  0.5819  0.5248  0.1687  0.1987
8       0.5889  0.6560  0.5092  0.5798  0.5411  0.1811  0.2073
9       0.5817  0.6541  0.5078  0.5757  0.5295  0.1707  0.1971
Mean    0.5817  0.6538  0.5135  0.5790  0.5320  0.1771  0.2027
Std     0.0070  0.0044  0.0124  0.0040  0.0177  0.0201  0.0123

CPU times: user 27.3 s, sys: 8.59 s, total: 35.9 s
Wall time: 1min 12s

In [ ]:
tuned_dt8

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage='auto',
                           solver='lsqr', store_covariance=False, tol=0.0001)

In [ ]:
predict_tuned_dt8 = predict_model(tuned_dt8, data=df_teste).Label

sub_csv = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/submission_format.csv")
sub_csv["damage_grade"] = predict_tuned_dt8
sub_csv.to_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/output/submit/predict_tuned_dt8.csv", index=False)

In [ ]:
%%time

tuned_dt9 = tune_model(dt9, optimize = 'F1')

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
Fold
0       0.5656  0.5774  0.3353  0.3417  0.4128  0.0008  0.0043
1       0.5651  0.5802  0.3340  0.3351  0.4121  0.0001  0.0005
2       0.5658  0.5761  0.3345  0.3378  0.4124  0.0008  0.0043
3       0.5653  0.5771  0.3337  0.3345  0.4119 -0.0002 -0.0010
4       0.5649  0.5804  0.3326  0.3293  0.4111 -0.0014 -0.0077
5       0.5652  0.5766  0.3347  0.3380  0.4124  0.0006  0.0033
6       0.5652  0.5799  0.3344  0.3361  0.4123  0.0008  0.0042
7       0.5653  0.5752  0.3346  0.3379  0.4124  0.0005  0.0029
8       0.5661  0.5744  0.3345  0.3389  0.4124  0.0008  0.0045
9       0.5657  0.5759  0.3347  0.3384  0.4125  0.0009  0.0049
Mean    0.5654  0.5773  0.3343  0.3368  0.4122  0.0004  0.0020
Std     0.0003  0.0020  0.0007  0.0032  0.0004  0.0007  0.0037

CPU times: user 5.17 s, sys: 259 ms, total: 5.43 s
Wall time: 10.7 s

In [ ]:
predict_tuned_dt9 = predict_model(tuned_dt9, data=df_teste).Label

sub_csv = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/submission_format.csv")
sub_csv["damage_grade"] = predict_tuned_dt9
sub_csv.to_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/output/submit/predict_tuned_dt9.csv", index=False)

In [ ]:
%%time

tuned_dt10 = tune_model(dt10, optimize = 'F1')

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
Fold
0       0.5764  0.6545  0.5114  0.5720  0.5485  0.1944  0.2074
1       0.5822  0.6641  0.5152  0.5771  0.5555  0.2060  0.2189
2       0.5788  0.6528  0.5075  0.5742  0.5538  0.2008  0.2126
3       0.5778  0.6569  0.5067  0.5759  0.5553  0.2018  0.2128
4       0.5725  0.6527  0.4958  0.5703  0.5467  0.1861  0.1981
5       0.5723  0.6492  0.5041  0.5680  0.5466  0.1884  0.2000
6       0.5715  0.6566  0.5046  0.5664  0.5469  0.1889  0.1998
7       0.5747  0.6539  0.5094  0.5704  0.5500  0.1943  0.2056
8       0.5761  0.6568  0.5106  0.5711  0.5508  0.1959  0.2075
9       0.5744  0.6521  0.5057  0.5703  0.5481  0.1914  0.2035
Mean    0.5757  0.6550  0.5071  0.5716  0.5502  0.1948  0.2066
Std     0.0031  0.0038  0.0050  0.0032  0.0033  0.0061  0.0063

CPU times: user 48.2 s, sys: 40.2 s, total: 1min 28s
Wall time: 1min 48s

In [ ]:
predict_tuned_dt10 = predict_model(tuned_dt10, data=df_teste).Label

sub_csv = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/data/submission_format.csv")
sub_csv["damage_grade"] = predict_tuned_dt10
sub_csv.to_csv("/content/drive/My Drive/Colab Notebooks/Richter's Predictor: Modeling Earthquake Damage/output/submit/predict_tuned_dt10.csv", index=False)